package uren.com.ilgincbilgiler.ContentClasses;

public class Human {

    String[] HUMAN_INFO = new String[]{
            "Beyin 10 Watt’lık bir ampul kadar enerji tüketiyor",
            "İnsan beyninin depolayabileceği bilgi miktarı Encyclopedia Britannica’nın içindeki bilgiden 5 kat fazla. Bilim adamları bir rakam belirleyemediler ama bu kapasitenin 3 ila 1000 Terabayt arasında olduğu düşünülüyor. 900 yıllık İngiliz Tarih Arşivi’nin 70 Terabayt olduğu düşünülürse, inanılmaz bir kapasiteden bahsediyoruz.",
            "Kadınların saç tellerinin kalınlığı, erkeklerinkinin yarısı kadardır. Garip gibi görünse de, tam da bu sebepten erkeklerin saçları pek “ipeksi” olamıyor. Saç teli kalınlığı ırka göre de değişebiliyor.",
            "Bir tel insan saçı, 100 gram taşıyabilir.",
            "En hızlı uzayan tırnak, orta parmağınızdaki tırnaktır. Daha da ilginci, çok kullanılan elin tarafındaki tırnağın da daha hızlı uzamasıdır. Neden böyle olduğu tam bilinmese de, uzun olan parmağın tırnağının daha hızlı, daha kısa parmakların tırnaklarının daha yavaş uzadığı gözlenmiştir.",
            "Vücudunuzda her santimetrekareye düşen tüy sayısı bir şempanzeninki ile aynıdır. Ama tabii ki insanların tüyleri çok daha açık renkli ve çoğu insanda önemli bir kısmı görünür değil.",
            "Sarışınların daha çok saçı vardır. Saç rengi, saçın gürlüğünü de etkiliyor. Ortalama bir insanın başında 100,000 saç kökü var ve her bir saç kökü insanın hayatı boyunca 20 ayrı saç üretebiliyor. Sarışınların ortalama 146,000 saç köküne karşılık, siyah saçlıların 110,000, kahverengi saçlıların 100,000 ve kızıl saçlıların 86,000 saç kökü var.",
            "İnsan kalbinin yarattığı basınç, kanı 10 metre yüksekliğe fışkırtmaya yeterlidir.",
            "Hapşırık hızı 160 km/saat’i geçebilir. İşte yine tam bu yüzden hapşırırken ağzınızı da kapatmanız gerekmektedir.",
            "Kadınlar gözlerini erkeklerden 2 kat daha fazla açıp kaparlar. Ortalama bir insan dakikada 13 kere gözünü kırpmaktadır.",
            "İç organlarınızın büyük bir kısmını kaybetseniz dahi hayatta kalabilirsiniz. İnsan vücudu çok kırılgan gibi görünmesine karşılık, mideniz, dalağınız, bir akciğeriniz veya böbreğiniz olmadan ya da karaciğerin %75’i, bağırsakların %80’i olmadan yaşamınızı sürdürebilirsiniz. Tabii ki çok iyi hissetmeyebilirsiniz ama bu organların eksikliği sizi öldürmeyecektir.",
            "Ayaklarda 500,000 ter bezi vardır ve günde yaklaşık 475 mililitre ter üretirler. Spor ayakkabınızın neden boyasının çıktığına şaşırmamanız lazım. Ayrıca, erkeklerde kadınlara göre daha fazla ter bezi bulunur.",
            "Her gün 120 milyon cinsel ilişki yaşanıyor.",
            "Dişleriniz siz doğmadan 6 ay önce gelişmeye başlar. Dişli olarak doğan bebek çok az ise de, dişlerin gelişimi çok erken başlıyor. 9 ila 12. haftada dişler şekilleniyor.",
            "Bütün bebeklerin gözü mavidir. Göz renginiz anne babanızdan kalıtımsal olarak geçse de, bebekler ilk olarak mavi gözlerle yaşama başlarlar. Bunun sebebi melanindir. Yeni doğan bebekte melanin henüz tam olarak stoklanmadığı ve koyulaşmadığından gözler mavi görünür. Zamanla gözler olması gereken renge dönüşür.",
            "Hamileliğin ilk üç ayında kadınların rüyada en çok gördükleri şeyler kurbağa, kurtçuk ve saksı bitkileridir. En çok görülen şeyler bunlar olsa da birçok kadın da su, doğum yapma, vahşet ya da seks ile ilgili rüyalar da görüyor.",
            "Kadınlar hem doğuştan itibaren, hem de yetişkinlikte erkeklerden daha iyi tat alır. Araştırmalar, kadınların bir kokuyu ayrıştırmada erkeklerden daha iyi olduğunu göstermiştir. Özellikle narenciye, vanilya, tarçın ve kahve kokularını kadınlar daha iyi alırlar. Nüfusun şanssız bir %2’lik kısmı ise hiç koku alamamaktadır.",
            "Burnunuz 50,000 farklı kokuyu tanıyabilir. Hayvanlara göre bu sayı daha mütevazi, örneğin bir tazının burnu insandan 1 milyon kere daha hassas ama yine de burnumuz faydasız değil. Hala çok sayıda kokuyu algılıyabiliyoruz ve bunları anılarımızla birleştirebiliyoruz.",
            "Gülümsemek için 17, kaşları çatmak için 43 kas çalışır.",
            "İnsan atıklarının yüzde 75’i sudur. İnsanın çıkardığı atıklarda sadece idrarın su içerdiğini sanıyorsanız yanılıyorsunuz. Dışkının da büyük kısmı sudur. Buna şükretmemiz lazım, zira böyle olmasaydı, sürekli acılı bir kabızlık çekerdik.",
            "İnsan yılda en az bin 460 rüya görür.",
            "İnsan kalbi dakikada 60-80 defa çarpar.",
            "İnsanın kalça kemiği betondan daha sağlamdır.",
            "Vücudumuzdaki tüm damarları uç uca ekleseniz 19 bin 200 kilometre eder.",
            "Bir insan yaşamı boyunca iki yüzme havuzunu dolduracak kadar tükürük salgılar.",
            "Erkekler kadınlara göre on kat daha fazla renk körü oluyorlar.",
            "Bir insan hayatı boyunca ortalama 22 kilogram deri kaybediyor.",
            "Her insanın dilinin izi de parmak izi gibi farklıdır.",
            "İnsanlar yaşamları boyunca altı filin ağırlığına eşit miktarda yiyecek tüketiyorlar.",
            "Her hapşırıkta, beyin hücrelerinin bir kısmı ölür.",
            "Vücudun kan kaynağı olmayan tek bölümü, gözdeki korneadır. Oksijeni doğrudan havadan alır.",
            "Yeni doğan bir bebek, yedinci aya dek aynı anda hem nefes alabilir hem yutkunabilir.",
            "Kafatası, 29 farklı kemikten meydana gelir.",
            "Beyinden gönderilen sinir sinyalleri, saatte 274 km hızla hareket eder.",
            "İnsan beyni, bir gün içerisinde dünyadaki tüm telefonların toplamından daha fazla elektrik sinyali üretir.",
            "Ortalama bir insan bedeninde, bir köpeğin üzerindeki tüm pireleri öldürecek kadar sülfür, 900 adet kalem yapacak kadar karbon, oyuncak bir topu ateşleyebilecek kadar potasyum, 7 adet sabun üretebilecek kadar yağ ve 50 litrelik bir varili doldurabilecek kadar su bulunur.",
            "İnsan kalbi, hayatı boyunca 182 milyon litre kan pompalar.",
            "Siz bu cümleyi okurken, vücudunuzda 50.000 hücre öldü ve yenileri ile değişti.",
            "İnsan embriyosu, gebeliğin ilk üç ayı içerisinde parmak izleri edinir.",
            "Kadın kalbi, erkek kalbinden daha hızlı atar.",
            "Charles Osborne adındaki bir adam, 68 yıl boyunca hıçkırmıştır.",
            "Sağlak insanlar, solaklara kıyasla ortalama 9 yıl daha fazla yaşarlar.",
            "Ortalama bir insan, rüyalarının yüzde 90'ını unutur.",
            "Bir insanın solunum hızı, ilkbahar ayında, sonbahar ayına kıyasla üçte bir oranında daha yüksektir.",
            "Vücut ısımızın yaklaşık yüzde 80'ini başımızdan kaybederiz.",
            "Vücut ağırlığınızın yüzde 1'ine denk gelecek miktarda su kaybettiğinizde, susuzluk hissi oluşmaya başlar. Yüzde 5'ten fazla kayıp bayılmaya, yüzde 10'dan fazla kayıp ise susuzluktan ölmeye sebep olur.",
            "İnsan bedeninde en az 700 enzim aktif bir şekilde çalışır.",
            "İnsan, sırt üstü uyuyabilen tek canlı türüdür.",
            "İnsan bedenindeki bakterilerin yalnızca yüzde 1'i hastalığa sebep olabilir.",
            "İnsan bedeninde kendi kendini iyileştiremeyen tek organ, diştir.",
            "Bir insan, uyumak için ortalama 7 dakikaya ihtiyaç duyar.",
            "İnsanların yalnızca yüzde 7'si solaktır.",
            "Elma ve muzun kokusu, kilo vermeye yardımcı olur.",
            "Bir insan, hayatı boyunca kazara ortalama sekiz küçük örümcek yutar.",
            "İnsan bedenindeki bakterilerin toplam ağırlığı, 2 kg'dır.",
            "İnsan bedenindeki kalsiyumun yüzde 99'u, dişlerde bulunur.",
            "Dudaklar, parmak uçlarından yüzlerce kat daha hassastır.",
            "Öpücük, kişinin nabzını dakikada 100 atışa kadar çıkarabilir.",
            "Çenenizin tek yanındaki çiğneme kaslarının toplam gücü, 195 kilograma denktir.",
            "Bir insan başka birini öptüğünde, 278 farklı bakteri türünün geçişine sebep olur. Neyse ki bunların yüzde 95'i zararsızdır.",
            "Günde bir paket sigara içmek, yılda yarım bardak katran içmeye denktir.",
            "Erkekler, kadınlara kıyasla iki kat daha fazla göz kırparlar.",
            "İnsan bedeninin yapısı, yalnızca dört mineral içerir: apatit, aragonit, kalsit ve kristobalit.",
            "Mavi gözlü insanlar, acıya karşı diğerlerine kıyasla daha hassastırlar.",
            "İnsan beyninde, her saniye içerisinde 100.000 kimyasal reaksiyon oluşur.",
            "Herkesin alt sırt bölgesinde gamzeler bulunur; ancak bunlar, bazı insanlarda daha belirgindir.",
            "Çift yumurta ikizlerinden birinde belirli bir diş yoksa, diğer ikizde de aynı dişten bulunmaz.",
            "Sarı saçlı bir erkeğin yüzündeki kıllar, koyu renklilere kıyasla daha hızlı uzarlar.",
            "İnsan bedenindeki akyuvarlar 2-3 gün boyunca yaşayabilirken, alyuvarlar 3-4 ay yaşayabilirler.",
            "İnsan bedenindeki en güçlü kas, dildir.",
            "İnsan kalbinin yaklaşık boyutu, kişinin yumruğuna eşittir. Yetişkin bir kalbin ağırlığı, 220-260 gr'dır.",
            "Doğumda, insan bedeninde 14 milyar hücre bulunur. Bu sayı, kişinin hayatı boyunca artmaz. 25 yıldan sonra, hücrelerin sayısı her gün 100.000 düşmeye başlar. 40 yıldan sonra ise beyindeki düşüş hızlanır ve 50 yılın sonunda nöronlar ve dolayısıyla beyin küçülmeye başlar.",
            "İnsan bedeninde ince bağırsak uzunluğu yaklaşık 2,5 m'dir. Ancak kişi öldükten sonra, bağırsak duvarlarındaki kaslar kendilerini bırakır ve bağırsak uzunluğu 6 m'ye çıkar.",
            "Sağ akciğer, sola kıyasla daha fazla hava alabilir.",
            "İnsanın ağzında yaklaşık 40,000 bakteri bulunur.",
            "İnsan gözü, 10 milyon farklı rengi ayırt edebilir.",
            "Bilim adamlarına göre IQ yükseldikçe daha fazla rüya görülüyor.",
            "Beyin herhangi bir acı hissetmez.",
            "Ortalama bir insan günde 60-100 saç teli kaybeder."
    };

    public Human() {

    }

    public String[] getHUMAN_INFO() {
        return HUMAN_INFO;
    }
}
